---

- debug: var=item.dest|dirname
  when: 
    - (item.type is defined)
    - item.type == 'file'
  with_items: "{{ i_svc.files }}"

- name: "{{ i_svc.name }} | file | create parent dirs"
  file:
    name: "{{ item.dest|dirname }}"
    state: directory
    recurse: yes
  with_items: "{{ i_svc.files }}"
  when: item.type == 'file'

- name: "{{ i_svc.name }} | file | copy files"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    directory_mode: yes
  when: 
    - (item.type is defined)
    - item.type == 'file'
  with_items: "{{ i_svc.files }}"

- name: "{{ i_svc.name }} | directory-present | create directories"
  file:
    name: "{{ item.dest }}"
    state: directory
    recurse: yes
  with_items: "{{ i_svc.files }}"
  when: item.type == 'directory-present'

- name: "{{ i_svc.name }} | directory | create parent dirs"
  file:
    name: "{{ item.dest }}"
    state: directory
    recurse: yes
  with_items: "{{ i_svc.files }}"
  when: item.type == 'directory'

- include: files-dir.yml
  when: item.type == 'directory'
  with_items: "{{ i_svc.files }}"
 